name: Update Top Languages

on:
  schedule:
    - cron: "0 0 * * *" # Jalan otomatis setiap jam 00:00 UTC (Pagi WIB)
  workflow_dispatch: # Supaya bisa di-klik "Run" manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Generate top languages card (pie)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          # GANTI 'elliottophellia' DENGAN USERNAME GITHUB KAMU DI BAWAH INI:
          options: "username=AerynnnSh&layout=pie&hide_border=true&langs_count=5&theme=transparent&title_color=539BF5&text_color=ADBAC7&text_bold=true"
          path: img/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit card
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          # Pastikan folder 'img' sudah ada, atau script ini akan membuatnya
          git add img/top-langs.svg
          git commit -m "chore: update top languages card" || exit 0
          git push
